CTECH-1527 Poll nuget for sdk and make test explicit

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -31,8 +31,30 @@ jobs:
           else
             exit 1
           fi
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v2
+
+      - name: Restore dependencies
+        run: |          
+          retries=2
+          found=0
+          while [[ $retries -ge 0 && $found == 0 ]]; do
+              if ! dotnet restore sdk/Finbourne.Access.Sdk.Extensions.sln ; then
+                  echo "[ERROR] unable to restore dependencies, attempts remaining: $retries"
+                  sleep 30
+                  ((retries--))
+              else
+                  echo "[INFO] successfully installed dependencies"
+                  found=1
+              fi
+          done
+          if [ $found == 0 ] ; then
+            echo "[ERROR] unable to restore dependencies"
+            exit 1
+          fi
       
-      - name: Run tests on MASTER branch
+      - name: Run tests
         if: ${{ github.base_ref == 'master' || github.ref == 'refs/heads/master' }}
         env: 
           FBN_TOKEN_URL: ${{ secrets.MASTER_FBN_TOKEN_URL }}
@@ -43,13 +65,7 @@ jobs:
           FBN_ACCESS_API_URL: ${{ secrets.MASTER_FBN_ACCESS_API_URL }}
           FBN_APP_NAME: ${{ secrets.MASTER_FBN_CLIENT_ID }}
           FBN_ACCESS_ACCESS_TOKEN: ${{ secrets.MASTER_FBN_ACCESS_TOKEN }}
-        run: | 
-          echo "env variables for MASTER have been set"
-          echo "Changing directory into sdk directory"
-          cd sdk          
-          echo "Running the tests..."
-          docker-compose up --abort-on-container-exit
-          echo "Tests COMPLETED"
+        run: dotnet test --configuration Release --verbosity normal sdk/Finbourne.Configuration.Sdk.Extensions.sln
 
       - name: Slack notification
         uses: 8398a7/action-slack@v3
